/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ChatBox: typeof import('./src/components/ChatBox.vue')['default']
    ChatPage: typeof import('./src/components/ChatPage.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElText: typeof import('element-plus/es')['ElText']
    Footers: typeof import('./src/components/Footers.vue')['default']
    Headers: typeof import('./src/components/Headers.vue')['default']
    Left: typeof import('./src/components/Left.vue')['default']
    Right: typeof import('./src/components/Right.vue')['default']
    RobotMsg: typeof import('./src/components/RobotMsg.vue')['default']
    UserMsg: typeof import('./src/components/UserMsg.vue')['default']
  }
}
